/// Example 12 — Repository Ingestion & Mindmap Generation
///
/// Demonstrates the `repo_ingest` tool in a two-step workflow:
///
///   1. `repo_ingest`  — walks the target directory, reads key files, extracts
///                       code outlines, and returns a rich markdown analysis.
///   2. Agent (LLM)    — reads the analysis and writes a Mermaid mindmap `.md`
///                       file that visually summarises the codebase.
///
/// The mindmap uses Mermaid's `mindmap` diagram type, which renders in GitHub,
/// VS Code (Mermaid Preview), and Obsidian out of the box.
///
/// Run (analyzes this repo itself):
///   cargo run --example 12_repo_mindmap
///
/// To analyse a different directory:
///   REPO_PATH=/path/to/your/project cargo run --example 12_repo_mindmap
use open_multi_agent_rs::{
    agent::Agent,
    create_adapter,
    tool::{built_in::register_built_in_tools, ToolExecutor, ToolRegistry},
    types::AgentConfig,
    AgentRunResult,
};
use std::sync::Arc;
use tokio::sync::Mutex;

fn api_key() -> String {
    dotenvy::dotenv().ok();
    std::env::var("OPENROUTER_API_KEY")
        .expect("OPENROUTER_API_KEY not set — add it to .env or export it")
        .trim_matches('"')
        .to_string()
}

#[tokio::main]
async fn main() {
    // ── Target repo to analyse ────────────────────────────────────────────────
    let repo_path = std::env::var("REPO_PATH")
        .unwrap_or_else(|_| ".".to_string());

    // ── Output: where to write the generated mindmap ──────────────────────────
    let output_file = std::env::var("OUTPUT_FILE")
        .unwrap_or_else(|_| "repo_mindmap.md".to_string());

    println!("Analyzing: {}", repo_path);
    println!("Output:    {}\n", output_file);

    // ── Tools ─────────────────────────────────────────────────────────────────
    let registry = Arc::new(Mutex::new(ToolRegistry::new()));
    {
        let mut reg = registry.lock().await;
        register_built_in_tools(&mut reg).await;
    }
    let executor = Arc::new(ToolExecutor::new(Arc::clone(&registry)));

    // ── Adapter ───────────────────────────────────────────────────────────────
    let adapter = Arc::from(create_adapter(
        "openrouter",
        Some(api_key()),
        Some("https://openrouter.ai/api/v1".to_string()),
    ));

    // ── Agent ─────────────────────────────────────────────────────────────────
    let config = AgentConfig {
        name: "repo-analyst".to_string(),
        model: "meta-llama/llama-3.1-8b-instruct".to_string(),
        system_prompt: Some(
            "You are a senior software architect who specialises in codebase analysis. \
             You have access to tools to read repositories and write files. \
             When asked to analyse a repo, always call repo_ingest first, \
             then produce a thorough Mermaid mindmap saved to the requested file. \
             \n\
             Mindmap format (use this exact structure):\n\
             ```markdown\n\
             # <Project Name> — Codebase Mindmap\n\
             \n\
             <!-- Generated by open-multi-agent-rs repo-analyst -->\n\
             \n\
             ```mermaid\n\
             mindmap\n\
               root(<Project Name>)\n\
                 <Category1>\n\
                   <Item1>\n\
                   <Item2>\n\
                 <Category2>\n\
                   ...\n\
             ```\n\
             \n\
             ## Summary\n\
             <2-3 paragraph plain-text summary of the project>\n\
             \n\
             ## Key Components\n\
             - **Component**: description\n\
             ```\n\
             \
             Be thorough but concise. Group related items. Cover: architecture, \
             modules/packages, key files, languages, dependencies, entry points, \
             data flows, and notable patterns.".to_string(),
        ),
        max_turns: Some(6),
        tools: Some(vec![
            "repo_ingest".to_string(),
            "file_write".to_string(),
            "file_read".to_string(),
        ]),
        ..Default::default()
    };

    let mut agent = Agent::new(config, Arc::clone(&registry), Arc::clone(&executor));

    // ── Prompt ────────────────────────────────────────────────────────────────
    let prompt = format!(
        "Analyse the repository at `{repo}` and create a comprehensive Mermaid mindmap. \
         Save it to `{out}`. \
         Steps:\n\
         1. Call repo_ingest with path=\"{repo}\" to get the full analysis.\n\
         2. Study the analysis carefully.\n\
         3. Write a rich Mermaid mindmap + summary to `{out}` using file_write.",
        repo = repo_path,
        out  = output_file,
    );

    println!("Starting analysis...\n{}\n", "─".repeat(60));

    match agent.run(&prompt, adapter).await {
        Ok(AgentRunResult { output, turns, token_usage, tool_calls, .. }) => {
            println!("{}", "─".repeat(60));
            println!("Done in {} turns", turns);
            println!("Tokens — input: {}, output: {}", token_usage.input_tokens, token_usage.output_tokens);
            println!("Tool calls:");
            for tc in &tool_calls {
                println!("  • {} ({}ms)", tc.tool_name, tc.duration_ms);
            }
            if !output.is_empty() {
                println!("\nAgent response:\n{}", output);
            }

            // Report which .md files were written by the agent.
            let written: Vec<_> = tool_calls.iter()
                .filter(|tc| tc.tool_name == "file_write")
                .filter_map(|tc| tc.input.get("path").and_then(|v| v.as_str()))
                .filter(|p| p.ends_with(".md"))
                .collect();

            if written.is_empty() {
                // Fall back to checking the requested filename.
                if std::path::Path::new(&output_file).exists() {
                    let size = std::fs::metadata(&output_file).map(|m| m.len()).unwrap_or(0);
                    println!("\n✓ Mindmap: `{}` ({} bytes)", output_file, size);
                } else {
                    println!("\n⚠ No .md file written — check agent output above.");
                }
            } else {
                for path in written {
                    let size = std::fs::metadata(path).map(|m| m.len()).unwrap_or(0);
                    println!("\n✓ Written: `{}` ({} bytes)", path, size);
                }
            }
        }
        Err(e) => eprintln!("Error: {}", e),
    }
}
